-- 第2阶段：方案执行反馈与案例回流
CREATE TABLE IF NOT EXISTS `blend_plan_feedback` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `plan_id` bigint NOT NULL COMMENT '关联方案ID',
  `order_id` bigint NOT NULL COMMENT '关联订单ID',
  `actual_quantity` decimal(12,2) NOT NULL COMMENT '实际执行量（吨）',
  `actual_ash` decimal(6,2) DEFAULT NULL COMMENT '实际灰分',
  `actual_sulfur` decimal(6,2) DEFAULT NULL COMMENT '实际硫分',
  `actual_moisture` decimal(6,2) DEFAULT NULL COMMENT '实际水分',
  `actual_volatile` decimal(6,2) DEFAULT NULL COMMENT '实际挥发分',
  `actual_calorific` decimal(10,2) DEFAULT NULL COMMENT '实际发热量',
  `actual_cost` decimal(12,2) DEFAULT NULL COMMENT '实际成本',
  `qualified_flag` tinyint NOT NULL DEFAULT 1 COMMENT '是否达标：1是，0否',
  `effectiveness_eval` varchar(50) DEFAULT NULL COMMENT '执行评价：优秀/良好/一般/较差',
  `feedback_desc` text COMMENT '反馈说明',
  `execute_date` date DEFAULT NULL COMMENT '执行日期',
  `operator_id` bigint DEFAULT NULL COMMENT '反馈录入人',
  `case_generated_flag` tinyint NOT NULL DEFAULT 0 COMMENT '是否已沉淀为案例：1是，0否',
  `case_id` bigint DEFAULT NULL COMMENT '回流生成的案例ID',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态：1有效，0无效',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_feedback_plan` (`plan_id`),
  KEY `idx_feedback_order` (`order_id`),
  KEY `idx_feedback_case` (`case_id`),
  CONSTRAINT `fk_feedback_plan` FOREIGN KEY (`plan_id`) REFERENCES `blend_plan` (`id`),
  CONSTRAINT `fk_feedback_order` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
  CONSTRAINT `fk_feedback_case` FOREIGN KEY (`case_id`) REFERENCES `case_sample` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='配煤方案执行反馈表';
